/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiSyncEventsRouteImport } from './routes/api/sync/events'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiSyncEventsRoute = ApiSyncEventsRouteImport.update({
  id: '/api/sync/events',
  path: '/api/sync/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/sync/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sync/events'
  id: '__root__' | '/_dashboard' | '/_dashboard/' | '/api/sync/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  ApiSyncEventsRoute: typeof ApiSyncEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/sync/events': {
      id: '/api/sync/events'
      path: '/api/sync/events'
      fullPath: '/api/sync/events'
      preLoaderRoute: typeof ApiSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  ApiSyncEventsRoute: ApiSyncEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
