/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiLogsIndexRouteImport } from './routes/api/logs/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/_dashboard/logs/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/_dashboard/events/index'
import { Route as ApiSyncEventsRouteImport } from './routes/api/sync/events'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiLogsIndexRoute = ApiLogsIndexRouteImport.update({
  id: '/api/logs/',
  path: '/api/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiSyncEventsRoute = ApiSyncEventsRouteImport.update({
  id: '/api/sync/events',
  path: '/api/sync/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
  '/events/': typeof DashboardEventsIndexRoute
  '/logs/': typeof DashboardLogsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/api/logs/': typeof ApiLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
  '/events': typeof DashboardEventsIndexRoute
  '/logs': typeof DashboardLogsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/api/logs': typeof ApiLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
  '/_dashboard/events/': typeof DashboardEventsIndexRoute
  '/_dashboard/logs/': typeof DashboardLogsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/api/logs/': typeof ApiLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/sync/events'
    | '/events/'
    | '/logs/'
    | '/settings/'
    | '/api/logs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sync/events' | '/events' | '/logs' | '/settings' | '/api/logs'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/'
    | '/api/sync/events'
    | '/_dashboard/events/'
    | '/_dashboard/logs/'
    | '/_dashboard/settings/'
    | '/api/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  ApiSyncEventsRoute: typeof ApiSyncEventsRoute
  ApiLogsIndexRoute: typeof ApiLogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/logs/': {
      id: '/api/logs/'
      path: '/api/logs'
      fullPath: '/api/logs/'
      preLoaderRoute: typeof ApiLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/logs/': {
      id: '/_dashboard/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/events/': {
      id: '/_dashboard/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/sync/events': {
      id: '/api/sync/events'
      path: '/api/sync/events'
      fullPath: '/api/sync/events'
      preLoaderRoute: typeof ApiSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  ApiSyncEventsRoute: ApiSyncEventsRoute,
  ApiLogsIndexRoute: ApiLogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
