/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiLogsIndexRouteImport } from './routes/api/logs/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardQueryDrivenIndexRouteImport } from './routes/_dashboard/query-driven/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/_dashboard/logs/index'
import { Route as DashboardDefaultIndexRouteImport } from './routes/_dashboard/default/index'
import { Route as DashboardCustomPaginationIndexRouteImport } from './routes/_dashboard/custom-pagination/index'
import { Route as ApiSyncEventsRouteImport } from './routes/api/sync/events'
import { Route as DashboardDefaultInfiniteRouteImport } from './routes/_dashboard/default/infinite'
import { Route as DashboardQueryDrivenMovieIndexRouteImport } from './routes/_dashboard/query-driven/$movie/index'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiLogsIndexRoute = ApiLogsIndexRouteImport.update({
  id: '/api/logs/',
  path: '/api/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardQueryDrivenIndexRoute =
  DashboardQueryDrivenIndexRouteImport.update({
    id: '/query-driven/',
    path: '/query-driven/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardDefaultIndexRoute = DashboardDefaultIndexRouteImport.update({
  id: '/default/',
  path: '/default/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardCustomPaginationIndexRoute =
  DashboardCustomPaginationIndexRouteImport.update({
    id: '/custom-pagination/',
    path: '/custom-pagination/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const ApiSyncEventsRoute = ApiSyncEventsRouteImport.update({
  id: '/api/sync/events',
  path: '/api/sync/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDefaultInfiniteRoute =
  DashboardDefaultInfiniteRouteImport.update({
    id: '/default/infinite',
    path: '/default/infinite',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardQueryDrivenMovieIndexRoute =
  DashboardQueryDrivenMovieIndexRouteImport.update({
    id: '/query-driven/$movie/',
    path: '/query-driven/$movie/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/default/infinite': typeof DashboardDefaultInfiniteRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
  '/custom-pagination/': typeof DashboardCustomPaginationIndexRoute
  '/default/': typeof DashboardDefaultIndexRoute
  '/logs/': typeof DashboardLogsIndexRoute
  '/query-driven/': typeof DashboardQueryDrivenIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/api/logs/': typeof ApiLogsIndexRoute
  '/query-driven/$movie/': typeof DashboardQueryDrivenMovieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/default/infinite': typeof DashboardDefaultInfiniteRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
  '/custom-pagination': typeof DashboardCustomPaginationIndexRoute
  '/default': typeof DashboardDefaultIndexRoute
  '/logs': typeof DashboardLogsIndexRoute
  '/query-driven': typeof DashboardQueryDrivenIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/api/logs': typeof ApiLogsIndexRoute
  '/query-driven/$movie': typeof DashboardQueryDrivenMovieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/default/infinite': typeof DashboardDefaultInfiniteRoute
  '/api/sync/events': typeof ApiSyncEventsRoute
  '/_dashboard/custom-pagination/': typeof DashboardCustomPaginationIndexRoute
  '/_dashboard/default/': typeof DashboardDefaultIndexRoute
  '/_dashboard/logs/': typeof DashboardLogsIndexRoute
  '/_dashboard/query-driven/': typeof DashboardQueryDrivenIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/api/logs/': typeof ApiLogsIndexRoute
  '/_dashboard/query-driven/$movie/': typeof DashboardQueryDrivenMovieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/default/infinite'
    | '/api/sync/events'
    | '/custom-pagination/'
    | '/default/'
    | '/logs/'
    | '/query-driven/'
    | '/settings/'
    | '/api/logs/'
    | '/query-driven/$movie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/default/infinite'
    | '/api/sync/events'
    | '/custom-pagination'
    | '/default'
    | '/logs'
    | '/query-driven'
    | '/settings'
    | '/api/logs'
    | '/query-driven/$movie'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/'
    | '/_dashboard/default/infinite'
    | '/api/sync/events'
    | '/_dashboard/custom-pagination/'
    | '/_dashboard/default/'
    | '/_dashboard/logs/'
    | '/_dashboard/query-driven/'
    | '/_dashboard/settings/'
    | '/api/logs/'
    | '/_dashboard/query-driven/$movie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  ApiSyncEventsRoute: typeof ApiSyncEventsRoute
  ApiLogsIndexRoute: typeof ApiLogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/logs/': {
      id: '/api/logs/'
      path: '/api/logs'
      fullPath: '/api/logs/'
      preLoaderRoute: typeof ApiLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/query-driven/': {
      id: '/_dashboard/query-driven/'
      path: '/query-driven'
      fullPath: '/query-driven/'
      preLoaderRoute: typeof DashboardQueryDrivenIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/logs/': {
      id: '/_dashboard/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/default/': {
      id: '/_dashboard/default/'
      path: '/default'
      fullPath: '/default/'
      preLoaderRoute: typeof DashboardDefaultIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/custom-pagination/': {
      id: '/_dashboard/custom-pagination/'
      path: '/custom-pagination'
      fullPath: '/custom-pagination/'
      preLoaderRoute: typeof DashboardCustomPaginationIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/sync/events': {
      id: '/api/sync/events'
      path: '/api/sync/events'
      fullPath: '/api/sync/events'
      preLoaderRoute: typeof ApiSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/default/infinite': {
      id: '/_dashboard/default/infinite'
      path: '/default/infinite'
      fullPath: '/default/infinite'
      preLoaderRoute: typeof DashboardDefaultInfiniteRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/query-driven/$movie/': {
      id: '/_dashboard/query-driven/$movie/'
      path: '/query-driven/$movie'
      fullPath: '/query-driven/$movie/'
      preLoaderRoute: typeof DashboardQueryDrivenMovieIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDefaultInfiniteRoute: typeof DashboardDefaultInfiniteRoute
  DashboardCustomPaginationIndexRoute: typeof DashboardCustomPaginationIndexRoute
  DashboardDefaultIndexRoute: typeof DashboardDefaultIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardQueryDrivenIndexRoute: typeof DashboardQueryDrivenIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardQueryDrivenMovieIndexRoute: typeof DashboardQueryDrivenMovieIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDefaultInfiniteRoute: DashboardDefaultInfiniteRoute,
  DashboardCustomPaginationIndexRoute: DashboardCustomPaginationIndexRoute,
  DashboardDefaultIndexRoute: DashboardDefaultIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardQueryDrivenIndexRoute: DashboardQueryDrivenIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardQueryDrivenMovieIndexRoute: DashboardQueryDrivenMovieIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  ApiSyncEventsRoute: ApiSyncEventsRoute,
  ApiLogsIndexRoute: ApiLogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
